@startuml
title Sequence diagram for Latency problem 3

participant ConsumerTest
participant Gateway
participant Greek
participant Roman
participant Nordic
participant Indian
participant Celtiberian

loop Stream
    ConsumerTest -> Gateway: GET /api/v1/gods/{god}

    Gateway -> Greek: GET /greek
    Greek --> Gateway: List of gods
    note over Gateway, Greek: or

    Gateway -> Roman: GET /roman
    Roman --> Gateway: List of gods
    note over Gateway, Roman: or

    Gateway -> Nordic: GET /nordic
    Nordic --> Gateway: List of gods
    note over Gateway, Nordic: or

    Gateway -> Indian: GET /indian
    Indian --> Gateway: List of gods
    note over Gateway, Indian: or

    Gateway -> Indian: GET /celtiberian
    Celtiberian --> Gateway: List of gods
    note over Gateway, Celtiberian: or

    Gateway --> ConsumerTest: List of gods

    ConsumerTest -> ConsumerTest: Assert
end loop
@enduml
