openapi: 3.0.3
info:
  title: Greek Gods REST API
  description: API for retrieving information about Greek gods
  version: 1.0.0
  contact:
    name: Juan Antonio Breña Moral
    email: my@email.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/v1/gods/greek:
    get:
      tags:
        - Greek Gods
      summary: Get all Greek gods
      description: Returns a list of Greek god names
      operationId: getGreekGods
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                    - "Zeus"
                    - "Hera"
                    - "Poseidon"
                    - "Demeter"
                    - "Ares"
                    - "Athena"
                    - "Apollo"
                    - "Artemis"
                    - "Hephaestus"
                    - "Aphrodite"
                    - "Hermes"
                    - "Dionysus"
                    - "Hades"
                    - "Hypnos"
                    - "Nike"
                    - "Janus"
                    - "Nemesis"
                    - "Iris"
                    - "Hecate"
                    - "Tyche"
        '500':
          description: Internal server error
components:
  schemas: {}