server:
  port: 8080

mythology:
  api:
    base-url: https://my-json-server.typicode.com/jabrena/latency-problems
    timeout: 10s

spring:
  application:
    name: god-information-gateway
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
    default-property-inclusion: NON_NULL

logging:
  level:
    info.jab.latency: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
