server:
  port: 8080

spring:
  application:
    name: greek-gods-api
  
  # Scheduling Configuration
  scheduling:
    enabled: true  # Enable/disable all scheduled tasks (default: true)
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/greek_gods_db
    username: greek_gods_user
    password: greek_gods_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  
  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
  
  # Spring Data JDBC Configuration
  data:
    jdbc:
      repositories:
        enabled: true

# External API Configuration for Background Sync
external-api:
  greek-gods:
    base-url: https://my-json-server.typicode.com
    endpoint: /jabrena/latency-problems/gods
    timeout: 30000  # 30 seconds

# Background Sync Scheduling Configuration
background-sync:
  greek-gods:
    enabled: true
    fixed-rate: 1800000  # 30 minutes = 30 * 60 * 1000 = 1800000 milliseconds
    initial-delay: 60000  # 1 minute initial delay = 60 * 1000 = 60000 milliseconds
    # Alternative cron expression (commented out - using fixed-rate by default)
    # cron: "0 */30 * * * *"  # Every 30 minutes

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  info:
    title: Greek Gods API
    description: REST API for retrieving Greek Gods data
    version: 1.0.0
    contact:
      name: Greek Gods API Team
      email: support@greekgodsapi.com
    license:
      name: MIT
      url: https://opensource.org/licenses/MIT

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    info.jab.latency: INFO
    org.springframework.jdbc: DEBUG
    org.flywaydb: INFO

---
# Production Profile
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/greek_gods_db}
    username: ${DATABASE_USER:greek_gods_user}
    password: ${DATABASE_PASSWORD:greek_gods_password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  
  # Production scheduling configuration
  scheduling:
    enabled: true  # Enable scheduling in production

# Production scheduling - less frequent sync
background-sync:
  greek-gods:
    enabled: true
    fixed-rate: 3600000  # 60 minutes = 60 * 60 * 1000 = 3600000 milliseconds
    initial-delay: 300000  # 5 minutes initial delay = 5 * 60 * 1000 = 300000 milliseconds

---
# Development Profile  
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5432/greek_gods_dev_db
    username: greek_gods_dev_user
    password: greek_gods_dev_password
  flyway:
    clean-disabled: false
  
  # Development scheduling configuration - can be disabled for testing
  scheduling:
    enabled: true  # Set to false to disable all scheduled tasks in development

# Development scheduling - more frequent sync for testing
background-sync:
  greek-gods:
    enabled: true
    fixed-rate: 300000  # 5 minutes = 5 * 60 * 1000 = 300000 milliseconds
    initial-delay: 30000  # 30 seconds initial delay = 30 * 1000 = 30000 milliseconds 