name: CI Builds

on: [push]

jobs:
  build:
    name: Build Problem ${{ matrix.problem.dir }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Continue other jobs even if one fails
      max-parallel: 5   # Run all problems simultaneously
      matrix:
        problem:
          - { dir: "problem1", path: "problem1/" }
          - { dir: "problem2", path: "problem2/" }
          - { dir: "problem3", path: "problem3/" }
          - { dir: "problem4", path: "problem4/" }
          - { dir: "problem5", path: "problem5/implementation" }
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetches all submodules
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '24'
          cache: 'maven'
      - name: Maven build ${{ matrix.problem.dir }}
        run: cd ${{ matrix.problem.path }} && ./mvnw --batch-mode --no-transfer-progress verify --file ./pom.xml