name: CI Builds

on: [push]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetches all submodules
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '24'
          cache: 'maven'
      - name: Maven build problem 1
        run: cd problem1/ && ./mvnw --batch-mode --no-transfer-progress verify --file ./pom.xml
      - name: Maven build problem 2
        run: cd problem2/ && ./mvnw --batch-mode --no-transfer-progress verify --file ./pom.xml
      - name: Maven build problem 3
        run: cd problem3/ && ./mvnw --batch-mode --no-transfer-progress verify --file ./pom.xml
      - name: Maven build problem 4
        run: cd problem4/ && ./mvnw --batch-mode --no-transfer-progress verify --file ./pom.xml
      - name: Maven build problem 5
        run: cd problem5/implementation && ./mvnw --batch-mode --no-transfer-progress verify --file ./pom.xml