name: CI Builds

on: [push]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetches all submodules
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '24'
      - name: Maven build problem 1
        run: ./backup/problem1/mvnw --batch-mode --no-transfer-progress verify --file ./backup/problem1/pom.xml
      - name: Maven build problem 2
        run: ./mvnw --batch-mode --no-transfer-progress verify --file ./pom.xml
